apiVersion: apps/v1
kind: Deployment 
metadata:
  name: python-app
 spec:
  selector:
    matchLabel:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    specs:
      containers:
      - name: python-app
        image: elontsi007/python-app1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
